//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceManagement.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\KeigoIto\\Documents\\Visual Studio 2013\\Projects\\AttendanceManagement\\Mast" +
            "erGetudo.xlsx")]
        public string ExcelPath_Getudo {
            get {
                return ((string)(this["ExcelPath_Getudo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\KeigoIto\\Documents\\Visual Studio 2013\\Projects\\AttendanceManagement\\Mast" +
            "erHoliday.xlsx")]
        public string ExcelPath_Holiday {
            get {
                return ((string)(this["ExcelPath_Holiday"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\KeigoIto\\Documents\\Visual Studio 2013\\Projects\\AttendanceManagement\\Atte" +
            "ndanceData.xlsx")]
        public string ExcelPath_Attendance {
            get {
                return ((string)(this["ExcelPath_Attendance"]));
            }
            set {
                this["ExcelPath_Attendance"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\KeigoIto\\Documents\\Visual Studio 2013\\Projects\\AttendanceManagement\\Atte" +
            "ndanceData.xlsx")]
        public string ExcelPath_AttendanceSample {
            get {
                return ((string)(this["ExcelPath_AttendanceSample"]));
            }
        }
    }
}
